### ISSUE TITLE
Error Running Against a Device

### ISSUE THREAD

**Issue by aalborz** [vrtadmin/smi_check#4]
I got the following error when I ran the tool against a device (Cisco switch), on which I had verified port 4786 is open:
=====================
I:\Tools & Scripts\Tools\Network\smi_check-master>smi_check.py --ip 10.2.0.33
[INFO] Sending TCP probe to 10.2.0.33:4786
Traceback (most recent call last):
  File "I:\Tools & Scripts\Tools\Network\smi_check-master\smi_check.py", line 98
, in <module>
    main()
  File "I:\Tools & Scripts\Tools\Network\smi_check-master\smi_check.py", line 57
, in main
    conn.send(req.decode('hex'))
AttributeError: 'str' object has no attribute 'decode'
======================

**Comment by Zvezdo4et** [comment]
Add this string:
import binascii

Replace:
conn.send(req.decode('hex')) -------> conn.send(binascii.unhexlify(req))
data.encode('hex') == resp --------> binascii.hexlify(data) == resp
